<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="2" failed="1" skipped="3">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-05-04T09:05:55Z" name="test_suite" finished-at="2020-05-04T09:07:10Z" duration-ms="75467">
    <groups>
    </groups>
    <test started-at="2020-05-04T09:05:55Z" name="Regression testing" finished-at="2020-05-04T09:07:10Z" duration-ms="75467">
      <class name="com.framework.testcases.AccountsPageTest">
        <test-method is-config="true" signature="startSession(java.lang.reflect.Method)[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:35:55Z" name="startSession" finished-at="2020-05-04T14:36:10Z" duration-ms="14869" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.testcases.AccountsPageTest.VerifyNoMode()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSession -->
        <test-method signature="VerifyNoMode()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:10Z" name="VerifyNoMode" finished-at="2020-05-04T14:36:10Z" duration-ms="171" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[These Tests are marked not to run in excel]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: These Tests are marked not to run in excel
	at com.framework.Listerners.ConditionalSkipTestAnalyzer.beforeInvocation(ConditionalSkipTestAnalyzer.java:20)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker$InvokeBeforeInvocationWithoutContextStrategy.callMethod(InvokedMethodListenerInvoker.java:84)
	at org.testng.internal.invokers.InvokedMethodListenerInvoker.invokeListener(InvokedMethodListenerInvoker.java:62)
	at org.testng.internal.Invoker.runInvokedMethodListeners(Invoker.java:566)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:644)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyNoMode -->
        <test-method is-config="true" signature="endSession()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:10Z" name="endSession" finished-at="2020-05-04T14:36:10Z" duration-ms="202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endSession -->
        <test-method is-config="true" signature="startSession(java.lang.reflect.Method)[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:10Z" name="startSession" finished-at="2020-05-04T14:36:23Z" duration-ms="13274" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.testcases.AccountsPageTest.VerifyTestFailure()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSession -->
        <test-method signature="VerifyTestFailure()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:23Z" name="VerifyTestFailure" finished-at="2020-05-04T14:36:23Z" duration-ms="86" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.framework.testcases.AccountsPageTest.VerifyTestFailure(AccountsPageTest.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTestFailure -->
        <test-method is-config="true" signature="endSession()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:23Z" name="endSession" finished-at="2020-05-04T14:36:28Z" duration-ms="4432" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endSession -->
        <test-method is-config="true" signature="startSession(java.lang.reflect.Method)[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:28Z" name="startSession" finished-at="2020-05-04T14:36:42Z" duration-ms="14213" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.testcases.AccountsPageTest.VerifyTestFailure()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSession -->
        <test-method signature="VerifyTestFailure()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:42Z" name="VerifyTestFailure" finished-at="2020-05-04T14:36:42Z" duration-ms="67" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.framework.testcases.AccountsPageTest.VerifyTestFailure(AccountsPageTest.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTestFailure -->
        <test-method is-config="true" signature="endSession()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:42Z" name="endSession" finished-at="2020-05-04T14:36:42Z" duration-ms="176" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endSession -->
        <test-method is-config="true" signature="startSession(java.lang.reflect.Method)[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:42Z" name="startSession" finished-at="2020-05-04T14:36:56Z" duration-ms="13460" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.testcases.AccountsPageTest.VerifyTestFailure()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSession -->
        <test-method signature="VerifyTestFailure()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:56Z" name="VerifyTestFailure" finished-at="2020-05-04T14:36:56Z" duration-ms="59" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.fail(Assert.java:100)
	at com.framework.testcases.AccountsPageTest.VerifyTestFailure(AccountsPageTest.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:1014)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1215)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyTestFailure -->
        <test-method is-config="true" signature="endSession()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:56Z" name="endSession" finished-at="2020-05-04T14:36:56Z" duration-ms="136" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endSession -->
        <test-method is-config="true" signature="startSession(java.lang.reflect.Method)[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:36:56Z" name="startSession" finished-at="2020-05-04T14:37:10Z" duration-ms="13421" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void com.framework.testcases.AccountsPageTest.VerifyValidation()]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startSession -->
        <test-method signature="VerifyValidation()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:37:10Z" name="VerifyValidation" finished-at="2020-05-04T14:37:10Z" duration-ms="69" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyValidation -->
        <test-method is-config="true" signature="endSession()[pri:0, instance:com.framework.testcases.AccountsPageTest@2c767a52]" started-at="2020-05-04T14:37:10Z" name="endSession" finished-at="2020-05-04T14:37:10Z" duration-ms="144" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- endSession -->
      </class> <!-- com.framework.testcases.AccountsPageTest -->
      <class name="com.framework.testcases.LoginPageTest">
        <test-method is-config="true" signature="setenvironmnet()[pri:0, instance:com.framework.testcases.LoginPageTest@130161f7]" started-at="2020-05-04T14:35:54Z" name="setenvironmnet" finished-at="2020-05-04T14:35:55Z" duration-ms="831" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setenvironmnet -->
        <test-method signature="verifyLogin()[pri:0, instance:com.framework.testcases.LoginPageTest@130161f7]" started-at="2020-05-04T14:37:10Z" name="verifyLogin" finished-at="2020-05-04T14:37:10Z" duration-ms="50" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyLogin -->
        <test-method is-config="true" signature="cleanUp()[pri:0, instance:com.framework.testcases.LoginPageTest@130161f7]" started-at="2020-05-04T14:37:11Z" name="cleanUp" finished-at="2020-05-04T14:37:11Z" duration-ms="52" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- cleanUp -->
      </class> <!-- com.framework.testcases.LoginPageTest -->
    </test> <!-- Regression testing -->
  </suite> <!-- test_suite -->
</testng-results>
